import type { Direction, EnemyDefinition, GridPoint, LevelData } from '../types/level'
import { isInsideRuntimePlayableArea } from '../utils/boardGeometry'
import { addPoints, directionVectors, samePoint } from '../utils/grid'

const PLAYER_SPEED = 5.6
const ENEMY_SPEED = 2.0
const LAST_ENEMY_SPEED_MULTIPLIER = 1.45
const BLOCK_PUSH_SPEED = 7.2
const PUSH_COOLDOWN_MS = 180
export const BLOCK_RESPAWN_INTERVAL_MS = 10000
export const BLOCK_RESPAWN_FADE_MS = 850
const ENEMY_PATH_DIRECTIONS: Direction[] = ['up', 'left', 'right', 'down']
const ENEMY_DIRECTION_PRIORITIES: Direction[][] = [
  ['left', 'right', 'up', 'down'],
  ['right', 'left', 'down', 'up']
]
const ENEMY_SPAWN_STAGGER_MS = 520
const ENEMY_DIG_DURATION_MS = 560
const ENEMY_RANDOMNESS_MARGIN = 2

export type EnemyPhase = 'spawning' | 'active' | 'digging'

/**
 * Continuous lane-travel state between two tile centers.
 *
 * Grid logic still treats `from` and `to` as authoritative occupancy anchors,
 * while `progress` provides the render layer with smooth in-between positions.
 */
export interface MotionState {
  from: GridPoint
  to: GridPoint
  direction: Direction
  progress: number
}

/** Shared runtime shape for any actor mirrored by the render layer. */
export interface ActorState {
  gridPosition: GridPoint
  worldPosition: GridPoint
  motion?: MotionState
}

export interface BlockState extends ActorState {
  id: string
  /** When present, the block keeps sliding tile-by-tile until it hits something. */
  slideDirection?: Direction
  source: 'original' | 'respawned'
  fadeInMs: number
}

export interface EnemyState extends ActorState {
  id: string
  type: EnemyDefinition['type']
  alive: boolean
  phase: EnemyPhase
  phaseTimerMs: number
  enraged: boolean
  pushedByBlockId?: string
  digTarget?: {
    blockId: string
    direction: Direction
  }
  /** Remembers the last committed move so the chase logic can avoid easy ping-pong reversals. */
  lastDirection?: Direction
}

export interface PlayerState extends ActorState {
  facing: Direction
  pushCooldownMs: number
}

/**
 * Authoritative pure gameplay snapshot for a single stage.
 *
 * This object is mutated only by pure core functions, then mirrored by the
 * Phaser scenes to keep gameplay rules testable and deterministic.
 */
export interface StageState {
  player: PlayerState
  blocks: BlockState[]
  enemies: EnemyState[]
  elapsedMs: number
  status: 'playing' | 'won' | 'lost'
  message: string
  rngSeed: number
  blockRespawnTimerMs: number
  nextRespawnedBlockIndex: number
}

/** Normalized real-time commands generated by the input layer each frame. */
export interface SimulationInput {
  moveDirection?: Direction
  pushDirection?: Direction
  throwDirection?: Direction
}

/** Per-step summary consumed by scenes for feedback and SFX decisions. */
export interface SimulationOutcome {
  pushedBlockId?: string
  destroyedBlockIds: string[]
  crushedEnemyIds: string[]
  pushedEnemyIds: string[]
  hatchedEnemyIds: string[]
  spawnedBlockIds: string[]
  playerMoved: boolean
  statusChanged: boolean
}

interface BlockActionResult {
  blockId: string
  crushedEnemyIds: string[]
  pushedEnemyIds: string[]
}

interface SlidingStepResult {
  moved: boolean
  crushedEnemyIds: string[]
  pushedEnemyIds: string[]
}

interface RankedEnemyMove {
  direction: Direction
  destination: GridPoint
  score: number
}

/** Creates the initial pure simulation state from authored level JSON. */
export function createStageState(level: LevelData): StageState {
  const enemies = level.enemies.map((enemy, index) => createEnemyState(`enemy-${index}`, enemy.type, enemy, index))
  const state: StageState = {
    player: createPlayerState(level.playerSpawn),
    blocks: level.blocks.map((block, index) => createBlockState(`block-${index}`, block, 'original')),
    enemies,
    elapsedMs: 0,
    status: 'playing',
    message: 'Keep moving. Crush every raider.',
    rngSeed: createInitialSeed(level),
    blockRespawnTimerMs: BLOCK_RESPAWN_INTERVAL_MS,
    nextRespawnedBlockIndex: 0
  }

  updateEnemyThreatState(state)
  state.message = describeState(state)
  return state
}

/**
 * Advances the stage simulation by one real-time delta.
 *
 * Order matters:
 * 1. update cooldowns and enemy lifecycle timers
 * 2. resolve player block actions
 * 3. start new player motion if movement is held
 * 4. choose enemy moves or digs for idle active enemies
 * 5. advance all in-flight motion
 * 6. recompute win/lose state and UI message
 */
export function stepStageState(level: LevelData, state: StageState, input: SimulationInput, deltaMs: number): SimulationOutcome {
  const outcome: SimulationOutcome = {
    destroyedBlockIds: [],
    crushedEnemyIds: [],
    pushedEnemyIds: [],
    hatchedEnemyIds: [],
    spawnedBlockIds: [],
    playerMoved: false,
    statusChanged: false
  }

  if (state.status !== 'playing') {
    return outcome
  }

  state.elapsedMs += deltaMs
  state.player.pushCooldownMs = Math.max(0, state.player.pushCooldownMs - deltaMs)
  updateEnemyThreatState(state)
  updateEnemyLifecycle(level, state, deltaMs, outcome)

  const actionDirection = input.throwDirection ?? input.pushDirection ?? input.moveDirection ?? state.player.facing
  if (actionDirection) {
    state.player.facing = actionDirection
  }

  let blockActionTaken = false
  if (input.throwDirection && state.player.pushCooldownMs <= 0 && !state.player.motion) {
    const throwResult = attemptBlockThrow(level, state, input.throwDirection)
    if (throwResult) {
      state.player.pushCooldownMs = PUSH_COOLDOWN_MS
      outcome.pushedBlockId = throwResult.blockId
      outcome.crushedEnemyIds.push(...throwResult.crushedEnemyIds)
      outcome.pushedEnemyIds.push(...throwResult.pushedEnemyIds)
      blockActionTaken = true
    }
  } else if (state.player.pushCooldownMs <= 0 && !state.player.motion) {
    const pushDirection = input.pushDirection ?? input.moveDirection
    const pushResult = pushDirection ? attemptPush(level, state, pushDirection) : undefined
    if (pushResult) {
      state.player.pushCooldownMs = PUSH_COOLDOWN_MS
      outcome.pushedBlockId = pushResult.blockId
      outcome.crushedEnemyIds.push(...pushResult.crushedEnemyIds)
      blockActionTaken = true
    } else if (pushDirection) {
      const jammedResult = attemptClassicBlockedPush(level, state, pushDirection)
      if (jammedResult) {
        state.player.pushCooldownMs = PUSH_COOLDOWN_MS
        outcome.destroyedBlockIds.push(jammedResult)
        blockActionTaken = true
      }
    }
  }

  if (input.moveDirection) {
    state.player.facing = input.moveDirection
  }

  if (input.moveDirection && !input.throwDirection && !state.player.motion && !blockActionTaken) {
    outcome.playerMoved = startPlayerMove(level, state, input.moveDirection)
  }

  for (const enemy of state.enemies) {
    if (!enemy.alive || enemy.motion || enemy.phase !== 'active') {
      continue
    }

    const rankedMoves = getRankedEnemyMoves(level, state, enemy)
    const shouldDig = shouldEnemyDig(level, state, enemy, rankedMoves)
    if (shouldDig) {
      startEnemyDig(level, state, enemy)
      continue
    }

    const direction = pickEnemyDirection(state, enemy, rankedMoves)
    if (direction) {
      enemy.lastDirection = direction
      enemy.pushedByBlockId = undefined
      startMotion(enemy, direction)
    }
  }

  advanceActor(state.player, PLAYER_SPEED, deltaMs)
  for (const block of state.blocks) {
    const blockOutcome = advanceBlock(level, state, block, deltaMs)
    outcome.crushedEnemyIds.push(...blockOutcome.crushedEnemyIds)
    outcome.pushedEnemyIds.push(...blockOutcome.pushedEnemyIds)
  }
  for (const enemy of state.enemies) {
    if (enemy.alive) {
      advanceActor(enemy, getEnemySpeed(enemy), deltaMs)
      if (!enemy.motion) {
        enemy.pushedByBlockId = undefined
      }
    }
  }

  updateBlockFadeIns(state, deltaMs)
  advanceRespawnBlocks(level, state, deltaMs, outcome)
  updateEnemyThreatState(state)
  const previousStatus = state.status
  updateStageStatus(state)
  state.message = describeState(state)
  outcome.statusChanged = previousStatus !== state.status
  outcome.crushedEnemyIds = uniqueIds(outcome.crushedEnemyIds)
  outcome.pushedEnemyIds = uniqueIds(outcome.pushedEnemyIds)
  outcome.hatchedEnemyIds = uniqueIds(outcome.hatchedEnemyIds)
  outcome.destroyedBlockIds = uniqueIds(outcome.destroyedBlockIds)
  outcome.spawnedBlockIds = uniqueIds(outcome.spawnedBlockIds)
  return outcome
}

export function describeState(state: StageState): string {
  if (state.status === 'won') {
    return 'Stage clear! Tap or press Enter to continue.'
  }

  if (state.status === 'lost') {
    return 'You were caught. Tap or press Enter to retry.'
  }

  const aliveEnemies = state.enemies.filter((enemy) => enemy.alive)
  const hatchingEnemies = aliveEnemies.filter((enemy) => enemy.phase === 'spawning')
  const diggingEnemies = aliveEnemies.filter((enemy) => enemy.phase === 'digging')

  if (aliveEnemies.length === 1 && aliveEnemies[0]?.enraged) {
    return 'Last raider is enraged. Keep moving.'
  }

  if (diggingEnemies.length > 0) {
    return 'Raiders are chewing through the ice. Break line of sight.'
  }

  if (hatchingEnemies.length > 0) {
    return 'More raiders are hatching. Stay mobile and keep them separated.'
  }

  return 'Raiders keep moving. Use blocks to crush them safely.'
}

function createPlayerState(spawn: GridPoint): PlayerState {
  return {
    gridPosition: { ...spawn },
    worldPosition: { ...spawn },
    facing: 'right',
    pushCooldownMs: 0
  }
}

function createBlockState(id: string, position: GridPoint, source: 'original' | 'respawned', fadeInMs = BLOCK_RESPAWN_FADE_MS): BlockState {
  return {
    id,
    source,
    fadeInMs,
    gridPosition: { ...position },
    worldPosition: { ...position }
  }
}

function createEnemyState(id: string, type: EnemyDefinition['type'], position: GridPoint, index: number): EnemyState {
  return {
    id,
    type,
    alive: true,
    phase: index === 0 ? 'active' : 'spawning',
    phaseTimerMs: index === 0 ? 0 : ENEMY_SPAWN_STAGGER_MS * index,
    enraged: false,
    gridPosition: { ...position },
    worldPosition: { ...position }
  }
}

function createInitialSeed(level: LevelData): number {
  let seed = 0x9e3779b9
  const seedPoints = [level.playerSpawn, ...level.blocks, ...level.enemies, ...(level.walls ?? [])]
  for (const point of seedPoints) {
    seed = Math.imul(seed ^ (point.x + 31), 1103515245)
    seed = Math.imul(seed ^ (point.y + 131), 12345)
  }
  return seed >>> 0
}

function nextRandom(state: StageState): number {
  state.rngSeed = (Math.imul(state.rngSeed, 1664525) + 1013904223) >>> 0
  return state.rngSeed / 0x100000000
}

function uniqueIds(ids: string[]): string[] {
  return [...new Set(ids)]
}

function updateEnemyThreatState(state: StageState): void {
  const aliveEnemies = state.enemies.filter((enemy) => enemy.alive)
  const isLastEnemy = aliveEnemies.length === 1
  for (const enemy of state.enemies) {
    enemy.enraged = isLastEnemy && enemy.alive
  }
}

function updateEnemyLifecycle(level: LevelData, state: StageState, deltaMs: number, outcome: SimulationOutcome): void {
  for (const enemy of state.enemies) {
    if (!enemy.alive) {
      continue
    }

    if (enemy.phase === 'spawning') {
      enemy.phaseTimerMs = Math.max(0, enemy.phaseTimerMs - deltaMs)
      if (enemy.phaseTimerMs <= 0) {
        enemy.phase = 'active'
        outcome.hatchedEnemyIds.push(enemy.id)
      }
      continue
    }

    if (enemy.phase !== 'digging') {
      continue
    }

    const digTarget = enemy.digTarget
    if (!digTarget) {
      enemy.phase = 'active'
      enemy.phaseTimerMs = 0
      continue
    }

    const block = state.blocks.find((candidate) => candidate.id === digTarget.blockId)
    const expectedCell = addPoints(enemy.gridPosition, directionVectors[digTarget.direction])
    if (!block || block.motion || !samePoint(block.gridPosition, expectedCell)) {
      enemy.phase = 'active'
      enemy.phaseTimerMs = 0
      enemy.digTarget = undefined
      continue
    }

    enemy.phaseTimerMs = Math.max(0, enemy.phaseTimerMs - deltaMs)
    if (enemy.phaseTimerMs > 0) {
      continue
    }

    if (destroyBlock(state, digTarget.blockId)) {
      outcome.destroyedBlockIds.push(digTarget.blockId)
    }

    enemy.phase = 'active'
    enemy.phaseTimerMs = 0
    enemy.digTarget = undefined
    enemy.pushedByBlockId = undefined
  }
}

function advanceActor(actor: ActorState, speedTilesPerSecond: number, deltaMs: number): void {
  if (!actor.motion) {
    actor.worldPosition = { ...actor.gridPosition }
    return
  }

  actor.motion.progress = Math.min(1, actor.motion.progress + (speedTilesPerSecond * deltaMs) / 1000)
  actor.worldPosition = interpolate(actor.motion.from, actor.motion.to, actor.motion.progress)

  if (actor.motion.progress >= 1) {
    actor.gridPosition = { ...actor.motion.to }
    actor.worldPosition = { ...actor.motion.to }
    actor.motion = undefined
  }
}

function interpolate(from: GridPoint, to: GridPoint, progress: number): GridPoint {
  return {
    x: from.x + (to.x - from.x) * progress,
    y: from.y + (to.y - from.y) * progress
  }
}

function attemptPush(level: LevelData, state: StageState, direction: Direction): BlockActionResult | undefined {
  const block = getAdjacentIdleBlock(state, direction)
  if (!block) {
    return undefined
  }

  const destination = addPoints(block.gridPosition, directionVectors[direction])
  if (!canBlockOccupy(level, state, destination, block.id)) {
    return undefined
  }

  const crushedEnemyIds = crushEnemiesInCell(state, destination)
  startMotion(block, direction)
  return {
    blockId: block.id,
    crushedEnemyIds,
    pushedEnemyIds: []
  }
}

function attemptClassicBlockedPush(level: LevelData, state: StageState, direction: Direction): string | undefined {
  const block = getImmovableAdjacentBlock(level, state, direction)
  if (!block) {
    return undefined
  }

  return destroyBlock(state, block.id) ? block.id : undefined
}

function attemptBlockThrow(level: LevelData, state: StageState, direction: Direction): BlockActionResult | undefined {
  const block = getAdjacentIdleBlock(state, direction)
  if (!block) {
    return undefined
  }

  block.slideDirection = direction
  const stepResult = startSlidingStep(level, state, block, direction)
  if (!stepResult.moved) {
    block.slideDirection = undefined
    return undefined
  }

  return {
    blockId: block.id,
    crushedEnemyIds: stepResult.crushedEnemyIds,
    pushedEnemyIds: stepResult.pushedEnemyIds
  }
}

function startSlidingStep(level: LevelData, state: StageState, block: BlockState, direction: Direction): SlidingStepResult {
  const next = addPoints(block.gridPosition, directionVectors[direction])
  if (!canSlideBlockInto(level, state, block.id, next)) {
    return {
      moved: false,
      crushedEnemyIds: [],
      pushedEnemyIds: []
    }
  }

  const enemyChain = getEnemyPushChain(state, next, direction)
  if (enemyChain.length === 0) {
    startMotion(block, direction)
    return {
      moved: true,
      crushedEnemyIds: [],
      pushedEnemyIds: []
    }
  }

  const crushedEnemyIds: string[] = []
  const pushedEnemyIds: string[] = []
  const chainTailDestination = addPoints(enemyChain[enemyChain.length - 1].point, directionVectors[direction])
  const shouldCrushTail = !canEnemyBeBlockPushedInto(level, state, enemyChain, chainTailDestination)

  for (let index = enemyChain.length - 1; index >= 0; index -= 1) {
    const entry = enemyChain[index]
    if (shouldCrushTail && index === enemyChain.length - 1) {
      crushEnemy(entry.enemy, entry.point)
      crushedEnemyIds.push(entry.enemy.id)
      continue
    }

    pushEnemyByBlock(entry.enemy, entry.point, direction, block.id)
    pushedEnemyIds.push(entry.enemy.id)
  }

  startMotion(block, direction)
  return {
    moved: true,
    crushedEnemyIds,
    pushedEnemyIds
  }
}

function startPlayerMove(level: LevelData, state: StageState, direction: Direction): boolean {
  const destination = addPoints(state.player.gridPosition, directionVectors[direction])
  if (!canActorOccupy(level, state, destination)) {
    return false
  }

  startMotion(state.player, direction)
  return true
}

function getRankedEnemyMoves(level: LevelData, state: StageState, enemy: EnemyState): RankedEnemyMove[] {
  const directions = getEnemyDirectionPriority(enemy.id)
  const playerTarget = state.player.motion?.to ?? state.player.gridPosition

  return directions
    .map((direction, index) => {
      const destination = addPoints(enemy.gridPosition, directionVectors[direction])
      if (!canEnemyOccupy(level, state, enemy.id, destination)) {
        return undefined
      }

      const pathDistance = getEnemyPathDistance(level, state, destination, playerTarget)
      const cannotPathPenalty = pathDistance === undefined ? 90 : 0
      const pathScore = (pathDistance ?? 9) * 10
      const manhattanScore = Math.abs(destination.x - playerTarget.x) + Math.abs(destination.y - playerTarget.y)
      const reversePenalty = enemy.lastDirection && isOppositeDirection(direction, enemy.lastDirection) ? 7 : 0
      return {
        direction,
        destination,
        score: cannotPathPenalty + pathScore + manhattanScore + reversePenalty + index
      } satisfies RankedEnemyMove
    })
    .filter((candidate): candidate is RankedEnemyMove => Boolean(candidate))
    .sort((a, b) => a.score - b.score)
}

function pickEnemyDirection(state: StageState, enemy: EnemyState, rankedMoves: RankedEnemyMove[]): Direction | undefined {
  if (rankedMoves.length === 0) {
    return undefined
  }

  const bestScore = rankedMoves[0].score
  const flexibleMoves = rankedMoves.filter((candidate) => candidate.score <= bestScore + ENEMY_RANDOMNESS_MARGIN)
  const randomIndex = Math.min(
    flexibleMoves.length - 1,
    Math.floor(Math.pow(nextRandom(state), 1.9) * flexibleMoves.length)
  )

  const chosen = flexibleMoves[randomIndex] ?? rankedMoves[0]
  const lastDirection = enemy.lastDirection
  if (flexibleMoves.length > 1 && lastDirection && isOppositeDirection(chosen.direction, lastDirection)) {
    return rankedMoves.find((candidate) => !isOppositeDirection(candidate.direction, lastDirection))?.direction ?? chosen.direction
  }

  return chosen.direction
}

function shouldEnemyDig(level: LevelData, state: StageState, enemy: EnemyState, rankedMoves: RankedEnemyMove[]): boolean {
  const digOptions = getDigCandidates(level, state, enemy)
  if (digOptions.length === 0) {
    return false
  }

  if (rankedMoves.length === 0) {
    return true
  }

  const bestPathDistance = getEnemyPathDistance(level, state, rankedMoves[0].destination, state.player.motion?.to ?? state.player.gridPosition)
  if (bestPathDistance === undefined) {
    return true
  }

  if (bestPathDistance >= 6) {
    return nextRandom(state) < 0.35
  }

  return false
}

function startEnemyDig(level: LevelData, state: StageState, enemy: EnemyState): void {
  const digCandidates = getDigCandidates(level, state, enemy)
  if (digCandidates.length === 0) {
    return
  }

  const playerTarget = state.player.motion?.to ?? state.player.gridPosition
  digCandidates.sort((a, b) => {
    const aDistance = Math.abs(a.destination.x - playerTarget.x) + Math.abs(a.destination.y - playerTarget.y)
    const bDistance = Math.abs(b.destination.x - playerTarget.x) + Math.abs(b.destination.y - playerTarget.y)
    return aDistance - bDistance
  })

  const chosen = digCandidates[Math.min(
    digCandidates.length - 1,
    Math.floor(Math.pow(nextRandom(state), 1.7) * digCandidates.length)
  )] as { blockId: string; direction: Direction; destination: GridPoint }

  enemy.phase = 'digging'
  enemy.phaseTimerMs = enemy.enraged ? ENEMY_DIG_DURATION_MS * 0.75 : ENEMY_DIG_DURATION_MS
  enemy.digTarget = {
    blockId: chosen.blockId,
    direction: chosen.direction
  }
  enemy.pushedByBlockId = undefined
}

function getDigCandidates(level: LevelData, state: StageState, enemy: EnemyState): Array<{ blockId: string; direction: Direction; destination: GridPoint }> {
  const playerTarget = state.player.motion?.to ?? state.player.gridPosition
  return getEnemyDirectionPriority(enemy.id)
    .map((direction) => {
      const destination = addPoints(enemy.gridPosition, directionVectors[direction])
      const block = state.blocks.find((candidate) => samePoint(candidate.gridPosition, destination) && !candidate.motion)
      if (!block || isWall(level, destination)) {
        return undefined
      }

      return {
        blockId: block.id,
        direction,
        destination
      }
    })
    .filter((candidate): candidate is { blockId: string; direction: Direction; destination: GridPoint } => Boolean(candidate))
    .sort((a, b) => {
      const aDistance = Math.abs(a.destination.x - playerTarget.x) + Math.abs(a.destination.y - playerTarget.y)
      const bDistance = Math.abs(b.destination.x - playerTarget.x) + Math.abs(b.destination.y - playerTarget.y)
      return aDistance - bDistance
    })
}

function getEnemyDirectionPriority(enemyId: string): Direction[] {
  const enemyIndex = Number(enemyId.split('-')[1] ?? '0')
  return ENEMY_DIRECTION_PRIORITIES[Math.abs(enemyIndex) % ENEMY_DIRECTION_PRIORITIES.length] as Direction[]
}

function getEnemyPathDistance(level: LevelData, state: StageState, start: GridPoint, target: GridPoint): number | undefined {
  if (samePoint(start, target)) {
    return 0
  }

  const queue: Array<{ point: GridPoint; distance: number }> = [{ point: start, distance: 0 }]
  const visited = new Set<string>([pointKey(start)])

  while (queue.length > 0) {
    const current = queue.shift() as { point: GridPoint; distance: number }

    for (const direction of ENEMY_PATH_DIRECTIONS) {
      const next = addPoints(current.point, directionVectors[direction])
      const nextKey = pointKey(next)
      if (visited.has(nextKey) || !canEnemyPathOccupy(level, state, next)) {
        continue
      }

      if (samePoint(next, target)) {
        return current.distance + 1
      }

      visited.add(nextKey)
      queue.push({
        point: next,
        distance: current.distance + 1
      })
    }
  }

  return undefined
}

function canEnemyPathOccupy(level: LevelData, state: StageState, point: GridPoint): boolean {
  return isInside(level, point)
    && !isWall(level, point)
    && !isBlockOccupyingCell(state.blocks, point)
}

function isOppositeDirection(a: Direction, b: Direction): boolean {
  return (a === 'left' && b === 'right')
    || (a === 'right' && b === 'left')
    || (a === 'up' && b === 'down')
    || (a === 'down' && b === 'up')
}

function pointKey(point: GridPoint): string {
  return `${point.x},${point.y}`
}

function getEnemySpeed(enemy: EnemyState): number {
  return enemy.enraged ? ENEMY_SPEED * LAST_ENEMY_SPEED_MULTIPLIER : ENEMY_SPEED
}

function canActorOccupy(level: LevelData, state: StageState, point: GridPoint): boolean {
  return isInside(level, point)
    && !isWall(level, point)
    && !isBlockOccupyingCell(state.blocks, point)
    && !isEnemyOccupyingCell(state.enemies, point)
}

function canEnemyOccupy(level: LevelData, state: StageState, enemyId: string, point: GridPoint): boolean {
  return isInside(level, point)
    && !isWall(level, point)
    && !isBlockOccupyingCell(state.blocks, point)
    && !state.enemies.some((enemy) => enemy.alive && enemy.id !== enemyId && occupiesCell(enemy, point))
}

function canBlockOccupy(level: LevelData, state: StageState, point: GridPoint, movingBlockId: string): boolean {
  return isInside(level, point)
    && !isWall(level, point)
    && !state.blocks.some((block) => block.id !== movingBlockId && occupiesCell(block, point))
}

function canSlideBlockInto(level: LevelData, state: StageState, movingBlockId: string, point: GridPoint): boolean {
  return isInside(level, point)
    && !isWall(level, point)
    && !state.blocks.some((block) => block.id !== movingBlockId && occupiesCell(block, point))
}

function canEnemyBeBlockPushedInto(
  level: LevelData,
  state: StageState,
  pushedChain: Array<{ enemy: EnemyState; point: GridPoint }>,
  point: GridPoint
): boolean {
  return isInside(level, point)
    && !isWall(level, point)
    && !state.blocks.some((block) => occupiesCell(block, point))
    && !state.enemies.some((enemy) => enemy.alive && !pushedChain.some((entry) => entry.enemy.id === enemy.id) && occupiesCell(enemy, point))
}

function getAdjacentIdleBlock(state: StageState, direction: Direction): BlockState | undefined {
  const blockOrigin = addPoints(state.player.gridPosition, directionVectors[direction])
  return state.blocks.find((candidate) => samePoint(candidate.gridPosition, blockOrigin) && !candidate.motion)
}

function getImmovableAdjacentBlock(level: LevelData, state: StageState, direction: Direction): BlockState | undefined {
  const block = getAdjacentIdleBlock(state, direction)
  if (!block) {
    return undefined
  }

  const destination = addPoints(block.gridPosition, directionVectors[direction])
  return canBlockOccupy(level, state, destination, block.id) ? undefined : block
}

function getEnemyPushChain(state: StageState, start: GridPoint, direction: Direction): Array<{ enemy: EnemyState; point: GridPoint }> {
  const chain: Array<{ enemy: EnemyState; point: GridPoint }> = []
  const visitedEnemyIds = new Set<string>()
  let cursor = { ...start }

  while (true) {
    const enemy = state.enemies.find((candidate) => candidate.alive && occupiesCell(candidate, cursor))
    if (!enemy || visitedEnemyIds.has(enemy.id)) {
      break
    }

    visitedEnemyIds.add(enemy.id)
    chain.push({
      enemy,
      point: { ...cursor }
    })
    cursor = addPoints(cursor, directionVectors[direction])
  }

  return chain
}

function crushEnemiesInCell(state: StageState, point: GridPoint): string[] {
  const crushedEnemyIds: string[] = []

  for (const enemy of state.enemies) {
    if (!enemy.alive || !occupiesCell(enemy, point)) {
      continue
    }

    crushEnemy(enemy, point)
    crushedEnemyIds.push(enemy.id)
  }

  return crushedEnemyIds
}

function crushEnemy(enemy: EnemyState, point: GridPoint): void {
  enemy.alive = false
  enemy.motion = undefined
  enemy.phase = 'active'
  enemy.phaseTimerMs = 0
  enemy.digTarget = undefined
  enemy.pushedByBlockId = undefined
  enemy.gridPosition = { ...point }
  enemy.worldPosition = { ...point }
}

function pushEnemyByBlock(enemy: EnemyState, point: GridPoint, direction: Direction, blockId: string): void {
  enemy.phase = 'active'
  enemy.phaseTimerMs = 0
  enemy.digTarget = undefined
  enemy.gridPosition = { ...point }
  enemy.worldPosition = { ...point }
  enemy.pushedByBlockId = blockId
  enemy.lastDirection = direction
  enemy.motion = {
    from: { ...point },
    to: addPoints(point, directionVectors[direction]),
    direction,
    progress: 0
  }
}

function startMotion(actor: ActorState, direction: Direction): void {
  const from = { ...actor.gridPosition }
  const to = addPoints(from, directionVectors[direction])
  actor.motion = {
    from,
    to,
    direction,
    progress: 0
  }
  actor.worldPosition = { ...from }
}

function advanceBlock(level: LevelData, state: StageState, block: BlockState, deltaMs: number): SlidingStepResult {
  const outcome: SlidingStepResult = {
    moved: false,
    crushedEnemyIds: [],
    pushedEnemyIds: []
  }

  advanceActor(block, BLOCK_PUSH_SPEED, deltaMs)
  if (block.motion || !block.slideDirection) {
    return outcome
  }

  const direction = block.slideDirection
  const nextStep = startSlidingStep(level, state, block, direction)
  if (!nextStep.moved) {
    block.slideDirection = undefined
  }

  return nextStep
}

function updateBlockFadeIns(state: StageState, deltaMs: number): void {
  for (const block of state.blocks) {
    if (block.fadeInMs >= BLOCK_RESPAWN_FADE_MS) {
      continue
    }

    block.fadeInMs = Math.min(BLOCK_RESPAWN_FADE_MS, block.fadeInMs + deltaMs)
  }
}

function advanceRespawnBlocks(
  level: LevelData,
  state: StageState,
  deltaMs: number,
  outcome: SimulationOutcome
): void {
  if (state.enemies.every((enemy) => !enemy.alive) || playerCaught(state)) {
    return
  }

  const hasOriginalBlocks = state.blocks.some((block) => block.source === 'original')
  const firstReplacementPending = !hasOriginalBlocks && state.nextRespawnedBlockIndex === 0

  if (hasOriginalBlocks) {
    state.blockRespawnTimerMs = BLOCK_RESPAWN_INTERVAL_MS
    return
  }

  if (firstReplacementPending) {
    state.blockRespawnTimerMs = 0
  }

  state.blockRespawnTimerMs = Math.max(0, state.blockRespawnTimerMs - deltaMs)
  if (state.blockRespawnTimerMs > 0) {
    return
  }

  while (state.blockRespawnTimerMs <= 0) {
    const spawnPoint = pickRespawnBlockPoint(level, state)
    if (!spawnPoint) {
      state.blockRespawnTimerMs = 0
      return
    }

    const blockId = `respawn-block-${state.nextRespawnedBlockIndex}`
    state.nextRespawnedBlockIndex += 1
    state.blocks.push(createBlockState(blockId, spawnPoint, 'respawned', 0))
    outcome.spawnedBlockIds.push(blockId)
    state.blockRespawnTimerMs += BLOCK_RESPAWN_INTERVAL_MS
  }
}

function pickRespawnBlockPoint(level: LevelData, state: StageState): GridPoint | undefined {
  const candidates: GridPoint[] = []

  for (let y = 0; y < level.height; y += 1) {
    for (let x = 0; x < level.width; x += 1) {
      const point = { x, y }
      if (!canSpawnRespawnedBlockAt(level, state, point)) {
        continue
      }

      candidates.push(point)
    }
  }

  if (candidates.length === 0) {
    return undefined
  }

  const index = Math.min(candidates.length - 1, Math.floor(nextRandom(state) * candidates.length))
  return { ...candidates[index] }
}

function canSpawnRespawnedBlockAt(level: LevelData, state: StageState, point: GridPoint): boolean {
  return isInside(level, point)
    && isInsideRuntimePlayableArea(point)
    && !isWall(level, point)
    && !occupiesCell(state.player, point)
    && !isBlockOccupyingCell(state.blocks, point)
    && !isEnemyOccupyingCell(state.enemies, point)
}

function destroyBlock(state: StageState, blockId: string): boolean {
  const previousLength = state.blocks.length
  state.blocks = state.blocks.filter((block) => block.id !== blockId)
  return state.blocks.length !== previousLength
}

function updateStageStatus(state: StageState): void {
  if (playerCaught(state)) {
    state.status = 'lost'
    return
  }

  if (state.enemies.every((enemy) => !enemy.alive)) {
    state.status = 'won'
    return
  }

  state.status = 'playing'
}

function playerCaught(state: StageState): boolean {
  for (const enemy of state.enemies) {
    if (!enemy.alive || enemy.phase === 'spawning') {
      continue
    }

    if (samePoint(enemy.gridPosition, state.player.gridPosition) && !enemy.motion && !state.player.motion) {
      return true
    }

    if (occupiesCell(enemy, state.player.gridPosition) || occupiesCell(state.player, enemy.gridPosition)) {
      return true
    }

    if (enemy.motion && state.player.motion) {
      const sameDestination = samePoint(enemy.motion.to, state.player.motion.to)
      const swapped = samePoint(enemy.motion.from, state.player.motion.to) && samePoint(enemy.motion.to, state.player.motion.from)
      if (sameDestination || swapped) {
        return true
      }
    }
  }

  return false
}

function isBlockOccupyingCell(blocks: BlockState[], point: GridPoint): boolean {
  return blocks.some((block) => occupiesCell(block, point))
}

function isEnemyOccupyingCell(enemies: EnemyState[], point: GridPoint): boolean {
  return enemies.some((enemy) => enemy.alive && occupiesCell(enemy, point))
}

function occupiesCell(actor: ActorState, point: GridPoint): boolean {
  if (samePoint(actor.gridPosition, point)) {
    return true
  }

  return actor.motion ? samePoint(actor.motion.to, point) : false
}

function isInside(level: LevelData, point: GridPoint): boolean {
  return point.x >= 0 && point.y >= 0 && point.x < level.width && point.y < level.height
}

function isWall(level: LevelData, point: GridPoint): boolean {
  return level.walls?.some((wall) => samePoint(wall, point)) ?? false
}
